sudo: false

language: go

go:
    - 1.6
    - tip

addons:
    apt:
        packages:
            - libhwloc-dev

install:
    - go get -t golang.org/x/net/context
    - go get -t github.com/docker/engine-api/client
    - go get -t github.com/docker/engine-api/types
    - go get -t github.com/Sirupsen/logrus
    - go get -t gopkg.in/urfave/cli.v2
